Fixes for Templated Queries and Linter Issues
aws/graph-explorer pull request #206
Opened 2023-10-17 20:54 UTC by cubeddu

Issue #197:

Description of changes:

- Updated fetch functionality for templated queries to use POST method.
- Resolved linter and pre-commit issues.
- Fixed a linter issue where SelectListBox node.value can be null.

These changes contribute towards resolving the bug reported in [Issue #197](https://github.com/aws/graph-explorer/issues/197) concerning long labels.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-19 23:05 UTC, Cole-Greer submitted a review, later dismissed
LGTM. As long as there are no concerns with the schema request I think this is good to go.

2023-10-19 23:05 UTC, Cole-Greer commented on packages/graph-explorer/src/connector/sparql/SPARQLConnector.ts
> +    const ops = { ...options, disableCache: true, method: "GET" };
Is the fetchSchema request the call to the summary API? If so I suppose there are no concerns with using a GET request for this.

2023-10-20 03:10 UTC, michaelnchin requested changes
Thanks @cubeddu ! Nice job on finding a workaround for the header limit. Couple of changes before we merge this in...

2023-10-20 19:21 UTC, michaelnchin requested changes

2023-11-15 19:03 UTC, cubeddu commented
@michaelnchin PR is ready for review.

2023-11-24 17:47 UTC, charlesivie submitted a review, later dismissed

2023-12-05 02:27 UTC, michaelnchin requested changes
Thanks @cubeddu ! Requesting a couple more changes per testing of the latest revision rebased on main.

**With IAM Auth enabled DB:**

Gremlin/OC/SPARQL connection sync queries are failing immediately with `AccessDeniedExpection` - requests are likely not being SigV4 signed correctly.

```
{
    "error": {
        "status": 500,
        "message": "\n{\n  \"detailedMessage\": \"Missing Authentication Token\",\n  \"code\": \"AccessDeniedException\",\n  \"requestId\": \"--\"\n}"
    }
}
```

**With non-IAM Auth DB:**

- On both Gremlin and OC connection sync, the initial `summary?mode=detailed` endpoint request fails with `BadRequestException`.

```
{
    "error": {
        "status": 500,
        "message": "\n{\n  \"detailedMessage\": \"Bad route: /pg/statistics/summary\",\n  \"code\": \"BadRequestException\",\n  \"requestId\": \"--\"\n}"
    }
}
```

- Gremlin sync is able to succeed via the fallback schema retrieval queries, but OC schema queries are terminated with different 500 error.

```
{
    "error": {
        "status": 500,
        "message": "\n{\n  \"detailedMessage\": \"Missing 'query' parameter for the request\",\n  \"code\": \"MissingParameterException\",\n  \"requestId\": \"--\"\n}"
    }
}
```

2023-12-08 20:19 UTC, cubeddu commented
> Thanks @cubeddu ! Requesting a couple more changes per testing of the latest revision rebased on main.
> 
> **With IAM Auth enabled DB:**
> 
> Gremlin/OC/SPARQL connection sync queries are failing immediately with `AccessDeniedExpection` - requests are likely not being SigV4 signed correctly.
> 
> ```
> {
>     "error": {
>         "status": 500,
>         "message": "\n{\n  \"detailedMessage\": \"Missing Authentication Token\",\n  \"code\": \"AccessDeniedException\",\n  \"requestId\": \"--\"\n}"
>     }
> }
> ```
> 
> **With non-IAM Auth DB:**
> 
> * On both Gremlin and OC connection sync, the initial `summary?mode=detailed` endpoint request fails with `BadRequestException`.
> 
> ```
> {
>     "error": {
>         "status": 500,
>         "message": "\n{\n  \"detailedMessage\": \"Bad route: /pg/statistics/summary\",\n  \"code\": \"BadRequestException\",\n  \"requestId\": \"--\"\n}"
>     }
> }
> ```
> 
> * Gremlin sync is able to succeed via the fallback schema retrieval queries, but OC schema queries are terminated with different 500 error.
> 
> ```
> {
>     "error": {
>         "status": 500,
>         "message": "\n{\n  \"detailedMessage\": \"Missing 'query' parameter for the request\",\n  \"code\": \"MissingParameterException\",\n  \"requestId\": \"--\"\n}"
>     }
> }
> ```

@michaelnchin @charlesivie changes are up, I addressed the issue and converted the signing of the headers to a middleware.

2024-01-05 01:49 UTC, michaelnchin approved these changes
LGTM, tested and working well. Thanks @cubeddu !

2024-01-05 22:01 UTC, merged